language: node_js
node_js: 15

os:
  - windows

arch:
  - amd64
  - arm64

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  npm: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

install:
  - npm install

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "$GITHUB_UNAME"
  - git config --local user.email "$GITHUB_EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(node -p -e "require('./package.json').version")-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG -m "Automatic release from Travis Ci"

deploy:
  provider: releases
  edge: true
  token:
    secure: "pATH+kf8r3eyjbN2AHRM+sJnvT5O91YlJnaBusPehsmEFQ4Ju2MkvTiorqv7lww8evIfU6YFGfAJoOedDJM+o0DICwC0xhCS8UNR97wD2OFkhbBsLgSsL2GEjtPGnfxkcpf0cjxIsVDoEwdYZleFO72wt+cip8YJaEs0ZmeVAO3CvtjvsMqA6tSUD1W+4ILFTHfUI3zFfIf1MMbfmD9F7j0vFUu409UIc7LxGYnSoe0v+4yeZvTc1qc2wTMXg89IkE1ovASf74nzGEktkMyzkj/2gVeMqzY4VsQxl5hJouAcIsdGmGWk3dyg6OPYCzMi2gM19YdeJ23e8p4MDtVKXhwOGcZxVf1ig6ahHBZUPuz6bnUnwMXWqPhvs5D4LYx4ORhbaTKme1fJjS438CJg28qrI6Z0TWoaMAPSPg3g3SQBaoXWdCAhZ15VtNdTW8tmgx/UJYWJZFmnViw3AzCAj0zp0PfcEXgF2fgO81pRQaCw0jKH8J7CDqH9XW6FfQTJH1SXDi/XOScRpQRGZ3PYX3EgFJa++CVlHpuwXbExp/P7Avww+SwUJwtODc44XpyyNNSdewn4zpCCFWwD5U5HdjvlEnTtISoaUZe4lkcJPcVyQMpAwidsR84wdntGinvGGRytEC8GzekTO0zhYYhotJvoh84JXOtCd6NyS3PCk0U="
  file_glob: true
  file:
    - "./dist/ZorroTracker*.tar.gz"
  draft: false
  on:
    tags: false
    branch:
      - main

script:
  - npm run travis_init
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run travis_test; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run travis_deploy; fi

notifications:
  email:
    on_success: never
    on_failure: never